apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongodb
  namespace: roboshop
  # Deployment labels
  labels:
    component: mongodb
    project: roboshop
    tier: database

spec:
  replicas: 1

  # These labels are used by ReplicaSet to select Pods.
  # They must match the Pod template labels.
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: database

  # Pod definition
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: database

    spec:
      containers:
        - name: mongodb
          image: shivapaturi01/mongodb:v1